// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJDRUdi4xlEguBCeGOA1Cxo7e7u7q6Fg',
    appId: '1:575224782536:web:e6d86e3b313887eef38ffd',
    messagingSenderId: '575224782536',
    projectId: 'needo-thesis',
    authDomain: 'needo-thesis.firebaseapp.com',
    storageBucket: 'needo-thesis.firebasestorage.app',
    measurementId: 'G-VN4X3VP9R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZQ3VCEVygUsKr2Xncw6uiLqe_2jp4zE',
    appId: '1:575224782536:android:be286ecd35c446cef38ffd',
    messagingSenderId: '575224782536',
    projectId: 'needo-thesis',
    storageBucket: 'needo-thesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhq4MAWR7-tuniQoy8SThOBOtip6whSuY',
    appId: '1:575224782536:ios:e920b15ddcea3f8ff38ffd',
    messagingSenderId: '575224782536',
    projectId: 'needo-thesis',
    storageBucket: 'needo-thesis.firebasestorage.app',
    iosBundleId: 'com.needo.needo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhq4MAWR7-tuniQoy8SThOBOtip6whSuY',
    appId: '1:575224782536:ios:e920b15ddcea3f8ff38ffd',
    messagingSenderId: '575224782536',
    projectId: 'needo-thesis',
    storageBucket: 'needo-thesis.firebasestorage.app',
    iosBundleId: 'com.needo.needo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlJDRUdi4xlEguBCeGOA1Cxo7e7u7q6Fg',
    appId: '1:575224782536:web:e435aba690696e92f38ffd',
    messagingSenderId: '575224782536',
    projectId: 'needo-thesis',
    authDomain: 'needo-thesis.firebaseapp.com',
    storageBucket: 'needo-thesis.firebasestorage.app',
    measurementId: 'G-X06GWH6CSR',
  );
}
